proxy:
  image: jwilder/nginx-proxy
  restart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"

btsyncdata:
  build: btsync
  entrypoint: /bin/echo
  command: data for btsync
  volumes:
    - /btsync
btsync:
  build: btsync
  command: docker-start
  restart: always
  hostname: btsync
  env_file: btsync/.env
  cap_add:
    - NET_ADMIN
  volumes:
    - /data:/data
  volumes_from:
    - btsyncdata
  ports:
    - "55555:55555"
  expose:
    - "8888"

ngrok:
  build: ngrok
  command: docker-start
  env_file: ngrok/.env
  net: host
  hostname: ngrok
  expose:
    - 4040
  cap_add:
    - NET_ADMIN

cadvisor:
  image: google/cadvisor:latest
  expose:
    - 8080
  env_file: .env.cadvisor
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

moviedownloads:
  image: busybox:latest
  command: true
  volumes:
    - /downloads/movies
showdownloads:
  image: busybox:latest
  command: true
  volumes:
    - /downloads/tv_shows

srtransmissiondata:
  build: transmission
  entrypoint: /bin/echo
  command: data for srtransmission
  volumes:
    - /transmission
srtransmission:
  build: transmission
  command: docker-start
  restart: always
  hostname: sr-transmission
  dns:
    - 209.222.18.222
    - 209.222.18.218
  cap_add:
    - MKNOD
    - NET_ADMIN
  expose:
    - 9091
  env_file: transmission/.sr.env
  volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - srtransmissiondata
    - showdownloads


cptransmissiondata:
  build: transmission
  entrypoint: /bin/echo
  command: data for cptransmission
  volumes:
    - /transmission
cptransmission:
  build: transmission
  command: docker-start
  restart: always
  hostname: cp-transmission
  dns:
    - 209.222.18.222
    - 209.222.18.218
  cap_add:
    - MKNOD
    - NET_ADMIN
  expose:
    - 9091
  env_file: transmission/.cp.env
  volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - cptransmissiondata
    - moviedownloads

sickrage:
  build: sickrage
  command: docker-start
  restart: always
  hostname: sickrage
  dns: 127.0.0.1
  links:
    - "srtransmission:transmission"
  cap_add:
    - NET_ADMIN
  ports:
    - "8081:8081"
  env_file: sickrage/.env
  volumes_from:
    - showdownloads
  volumes:
    - /data/tv_shows:/tv_shows
    - /opt/sickrage:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro

couchpotato:
  build: couchpotato
  command: docker-start
  restart: always
  hostname: couchpotato
  dns: 127.0.0.1
  links:
    - "cptransmission:transmission"
  cap_add:
    - NET_ADMIN
  ports:
    - "5050:5050"
  env_file: couchpotato/.env
  volumes_from:
    - moviedownloads
  volumes:
    - /data/movies:/movies
    - /opt/couchpotato:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro

plex:
  build: plex
  command: docker-start
  restart: always
  hostname: plexmediaserver
  env_file: plex/.env
  ports:
    - "32400:32400"
    - "1900:1900/udp"
    - "3005:3005"
    - "5353:5353/udp"
    - "8324:8324"
    - "32410:32410/udp"
    - "32411:32411/udp"
    - "32412:32412/udp"
    - "32413:32413/udp"
    - "32414:32414/udp"
    - "32469:32469"
  volumes:
    - /data:/data
    - /opt/plex:/plexmediaserver
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  cap_add:
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW
