localtime:
  image: busybox:latest
  command: true
  volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro

proxy:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"

btsyncdata:
  build: btsync
  entrypoint: /bin/echo
  command: data for btsync
  volumes:
    - /btsync
btsync:
  build: btsync
  command: docker-start
  hostname: btsync
  env_file: btsync/.env
  cap_add:
    - NET_ADMIN
  volumes:
    - /data:/data
  volumes_from:
    - btsyncdata
  ports:
    - "55555:55555"
  expose:
    - "8888"

ngrok:
  build: ngrok
  command: docker-start
  env_file: ngrok/.env
  net: host
  hostname: ngrok
  cap_add:
    - NET_ADMIN

cadvisor:
  image: google/cadvisor:latest
  expose:
    - 8080
  env_file: .env.cadvisor
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

transmission:
  build: transmission
  command: docker-start
  hostname: transmission
  cap_add:
    - MKNOD
    - NET_ADMIN
  expose:
    - 9091
  env_file: transmission/.env
  volumes_from:
    - localtime
  volumes:
    - /downloads

sickragedata:
  build: sickrage
  entrypoint: /bin/echo
  command: data for sickrage
  volumes:
    - /data
sickrage:
  build: sickrage
  command: docker-start
  hostname: sickrage
  dns: 127.0.0.1
  cap_add:
    - NET_ADMIN
  ports:
    - "8081:8081"
  env_file: sickrage/.env
  volumes_from:
    - localtime
    - sickragedata
    - transmission
  volumes:
    - /data/tv_shows:/tv_shows

couchpotatodata:
  build: couchpotato
  entrypoint: /bin/echo
  command: data for couchpotato
  volumes:
    - /data
couchpotato:
  build: couchpotato
  command: docker-start
  hostname: couchpotato
  dns: 127.0.0.1
  cap_add:
    - NET_ADMIN
  ports:
    - "5050:5050"
  env_file: couchpotato/.env
  volumes_from:
    - localtime
    - couchpotatodata
    - transmission
  volumes:
    - /data/movies:/movies

plexdata:
  build: plex
  entrypoint: /bin/echo
  command: data for plex
  volumes:
    - /plexmediaserver
plex:
  build: plex
  command: docker-start
  hostname: plexmediaserver
  env_file: plex/.env
  ports:
    - "32400:32400"
    - "1900:1900/udp"
    - "3005:3005"
    - "5353:5353/udp"
    - "8324:8324"
    - "32410:32410/udp"
    - "32411:32411/udp"
    - "32412:32412/udp"
    - "32413:32413/udp"
    - "32414:32414/udp"
    - "32469:32469"
  volumes:
    - /data:/data
  volumes_from:
    - localtime
    - plexdata
  cap_add:
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW

