#!/bin/bash
set -eo pipefail
trap "exit 0" 2 15

if [ -z "$PLEX_USERNAME" ] || [ -z "$PLEX_PASSWORD" ]; then
  echo "==> No Plex Pass credentials, using public update channel"
  export PUBLIC=yes
fi

/usr/local/bin/plexupdate.sh
exec -a "supervisord" "/usr/bin/supervisord" "-c" "/etc/supervisor/supervisord.conf"
exit 0
