#!/bin/bash
set -eo pipefail
trap "exit 0" 2 15

echo "**** Starting Sickrage (https://www.sickrage.tv) container. Enjoy! ****"
[ -n "$OPEN_FILE_LIMIT" ] &&\
  ulimit -n $OPEN_FILE_LIMIT

t2 -template-dir /templates -delete
exec $*
exit 0
